name: payung_teduh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: 2.0.10+1
  timeline_tile: 2.0.0
  intl: 0.19.0
  image_picker: 1.1.2
  shared_preferences: 2.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icon/
    - assets/svg/
  uses-material-design: true

